# ============================================================
# vMix-Yamaha TF3 Bridge - Post-Install Configuration
# ============================================================
# Called by the Inno Setup installer after files are copied.
# Handles Python setup, backend venv, .env configuration,
# optional network configuration, and install folder permissions.
# ============================================================

param(
    [Parameter(Mandatory = $true)]
    [string]$InstallDir,

    [string]$PCIP = "192.168.1.50",
    [string]$YamahaIP = "192.168.1.3",
    [string]$VMixIP = "192.168.1.50",
    [string]$PythonExe = ""
)

$ErrorActionPreference = "Continue"
$logFile = Join-Path $InstallDir "install.log"

function Write-Log {
    param([string]$Message)

    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$ts | $Message" | Out-File -FilePath $logFile -Append -Encoding utf8
}

function Refresh-Path {
    $machinePath = [System.Environment]::GetEnvironmentVariable("PATH", "Machine")
    $userPath = [System.Environment]::GetEnvironmentVariable("PATH", "User")
    $env:PATH = "$machinePath;$userPath"
}

function Resolve-PythonCommand {
    $py = Get-Command "py.exe" -ErrorAction SilentlyContinue
    if ($py) {
        return @{ File = $py.Source; PrefixArgs = @("-3") }
    }

    $python = Get-Command "python.exe" -ErrorAction SilentlyContinue
    if ($python) {
        return @{ File = $python.Source; PrefixArgs = @() }
    }

    $commonPaths = @(
        "C:\Program Files\Python313\python.exe",
        "C:\Program Files\Python312\python.exe",
        "C:\Program Files\Python311\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python313\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python312\python.exe",
        "$env:LOCALAPPDATA\Programs\Python\Python311\python.exe"
    )

    foreach ($path in $commonPaths) {
        if (Test-Path $path) {
            return @{ File = $path; PrefixArgs = @() }
        }
    }

    return $null
}

function Invoke-Python {
    param(
        [hashtable]$PythonCommand,
        [string[]]$Arguments
    )

    $allArgs = @()
    if ($PythonCommand.PrefixArgs) {
        $allArgs += $PythonCommand.PrefixArgs
    }
    $allArgs += $Arguments

    & $PythonCommand.File @allArgs 2>&1 |
        ForEach-Object { Write-Log "python: $_" }
    return $LASTEXITCODE
}

Write-Log "============================================"
Write-Log "vMix-Yamaha TF3 Bridge - Post-Install"
Write-Log "============================================"
Write-Log "Install Dir : $InstallDir"
Write-Log "PC IP       : $PCIP"
Write-Log "Yamaha IP   : $YamahaIP"
Write-Log "vMix IP     : $VMixIP"
Write-Log ""

Write-Log "[1/6] Checking Python..."
$pythonCommand = Resolve-PythonCommand

if (-not $pythonCommand) {
    Write-Log "Python not found. Installing bundled Python..."
    if ($PythonExe -and (Test-Path $PythonExe)) {
        $proc = Start-Process $PythonExe `
            -ArgumentList "/quiet InstallAllUsers=1 PrependPath=1 Include_pip=1 Include_launcher=1" `
            -Wait -PassThru -WindowStyle Hidden
        Write-Log "Python installer exited with code: $($proc.ExitCode)"
        Refresh-Path
        $pythonCommand = Resolve-PythonCommand
    } else {
        Write-Log "ERROR: Python installer not found at: $PythonExe"
    }
}

if ($pythonCommand) {
    Write-Log "Python command: $($pythonCommand.File) $($pythonCommand.PrefixArgs -join ' ')"
} else {
    Write-Log "ERROR: Python is still unavailable. Backend setup cannot continue."
}

Write-Log "[2/6] Writing backend .env configuration..."
$backendDir = Join-Path $InstallDir "backend"
$envPath = Join-Path $backendDir ".env"
$envContent = @"
# vMix-Yamaha TF3 Bridge Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

VMIX_HOST=$VMixIP
VMIX_TCP_PORT=8099
VMIX_HTTP_PORT=8088

YAMAHA_HOST=$YamahaIP
YAMAHA_PORT=49280

RECONNECT_INITIAL_DELAY=1.0
RECONNECT_MAX_DELAY=30.0
RECONNECT_BACKOFF_FACTOR=2.0
"@

try {
    [System.IO.Directory]::CreateDirectory($backendDir) | Out-Null
    [System.IO.File]::WriteAllText($envPath, $envContent, [System.Text.Encoding]::UTF8)
    Write-Log ".env written to: $envPath"
} catch {
    Write-Log "ERROR writing .env: $_"
}

Write-Log "[3/6] Setting up Python virtual environment..."
if ($pythonCommand) {
    try {
        Push-Location $backendDir

        $venvExitCode = Invoke-Python -PythonCommand $pythonCommand -Arguments @("-m", "venv", ".venv")
        if ($venvExitCode -ne 0) {
            Write-Log "ERROR: venv creation failed with code $venvExitCode"
        } else {
            Write-Log "Virtual environment created."
        }

        $venvPython = Join-Path $backendDir ".venv\Scripts\python.exe"
        if (-not (Test-Path $venvPython)) {
            $venvPython = Join-Path $backendDir ".venv\bin\python.exe"
        }

        if (Test-Path $venvPython) {
            Write-Log "Installing backend packages..."
            & $venvPython -m pip install --upgrade pip 2>&1 |
                ForEach-Object { Write-Log "pip: $_" }
            & $venvPython -m pip install --no-cache-dir -r requirements.txt 2>&1 |
                ForEach-Object { Write-Log "pip: $_" }
            Write-Log "Backend packages installed."
        } else {
            Write-Log "ERROR: venv Python not found at: $venvPython"
        }

        Pop-Location
    } catch {
        Write-Log "ERROR creating backend venv: $_"
        Pop-Location
    }
}

Write-Log "[4/6] Configuring Ethernet adapter..."
try {
    $adapter = Get-NetAdapter -Physical -ErrorAction SilentlyContinue |
               Where-Object { $_.MediaType -eq "802.3" } |
               Select-Object -First 1

    if (-not $adapter) {
        $adapter = Get-NetAdapter -ErrorAction SilentlyContinue |
                   Where-Object { $_.Name -like "Ethernet*" -or $_.Name -like "Local Area*" } |
                   Select-Object -First 1
    }

    if ($adapter) {
        Write-Log "Found adapter: $($adapter.Name) [$($adapter.InterfaceDescription)]"
        & netsh interface ip set address name="$($adapter.Name)" static $PCIP 255.255.255.0 192.168.1.1 2>&1 |
            ForEach-Object { Write-Log "netsh: $_" }
        Write-Log "Static IP configured: $PCIP / 255.255.255.0 / 192.168.1.1"
    } else {
        Write-Log "WARNING: No Ethernet adapter found."
        Write-Log "Configure manually if needed: IP $PCIP, subnet 255.255.255.0, gateway 192.168.1.1"
    }
} catch {
    Write-Log "ERROR configuring network: $_"
}

Write-Log "[5/6] Setting install folder permissions..."
try {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    & icacls $InstallDir /grant "${currentUser}:(OI)(CI)F" /T /Q 2>&1 |
        ForEach-Object { Write-Log "icacls: $_" }
    Write-Log "Full control granted to: $currentUser"
} catch {
    Write-Log "ERROR setting permissions: $_"
}

Write-Log "[6/6] Verifying packaged frontend..."
$frontendIndex = Join-Path $InstallDir "frontend\dist\index.html"
if (Test-Path $frontendIndex) {
    Write-Log "Frontend build found: $frontendIndex"
} else {
    Write-Log "ERROR: Frontend build missing: $frontendIndex"
}

Write-Log ""
Write-Log "============================================"
Write-Log "Post-install complete"
Write-Log "============================================"
