# ============================================================
# vMix-Yamaha TF3 Bridge - Post-Install Configuration
# ============================================================
# Called by the Inno Setup installer after files are copied.
# Handles .env configuration, optional network configuration, 
# and install folder permissions.
# ============================================================

param(
    [Parameter(Mandatory = $true)]
    [string]$InstallDir,

    [string]$PCIP = "192.168.1.50",
    [string]$YamahaIP = "192.168.1.3",
    [string]$VMixIP = "192.168.1.50"
)

$ErrorActionPreference = "Continue"
$logFile = Join-Path $InstallDir "install.log"

function Write-Log {
    param([string]$Message)

    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$ts | $Message" | Out-File -FilePath $logFile -Append -Encoding utf8
}

Write-Log "============================================"
Write-Log "vMix-Yamaha TF3 Bridge - Post-Install"
Write-Log "============================================"
Write-Log "Install Dir : $InstallDir"
Write-Log "PC IP       : $PCIP"
Write-Log "Yamaha IP   : $YamahaIP"
Write-Log "vMix IP     : $VMixIP"
Write-Log ""

Write-Log "[1/3] Writing backend .env configuration..."
$envPath = Join-Path $InstallDir ".env"
$envContent = @"
# vMix-Yamaha TF3 Bridge Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

VMIX_HOST=$VMixIP
VMIX_TCP_PORT=8099
VMIX_HTTP_PORT=8088

YAMAHA_HOST=$YamahaIP
YAMAHA_PORT=49280

RECONNECT_INITIAL_DELAY=1.0
RECONNECT_MAX_DELAY=30.0
RECONNECT_BACKOFF_FACTOR=2.0
"@

try {
    [System.IO.File]::WriteAllText($envPath, $envContent, [System.Text.Encoding]::UTF8)
    Write-Log ".env written to: $envPath"
} catch {
    Write-Log "ERROR writing .env: $_"
}

Write-Log "[2/3] Configuring Ethernet adapter..."
try {
    $adapter = Get-NetAdapter -Physical -ErrorAction SilentlyContinue |
               Where-Object { $_.MediaType -eq "802.3" } |
               Select-Object -First 1

    if (-not $adapter) {
        $adapter = Get-NetAdapter -ErrorAction SilentlyContinue |
                   Where-Object { $_.Name -like "Ethernet*" -or $_.Name -like "Local Area*" } |
                   Select-Object -First 1
    }

    if ($adapter) {
        Write-Log "Found adapter: $($adapter.Name) [$($adapter.InterfaceDescription)]"
        & netsh interface ip set address name="$($adapter.Name)" static $PCIP 255.255.255.0 192.168.1.1 2>&1 |
            ForEach-Object { Write-Log "netsh: $_" }
        Write-Log "Static IP configured: $PCIP / 255.255.255.0 / 192.168.1.1"
    } else {
        Write-Log "WARNING: No Ethernet adapter found."
        Write-Log "Configure manually if needed: IP $PCIP, subnet 255.255.255.0, gateway 192.168.1.1"
    }
} catch {
    Write-Log "ERROR configuring network: $_"
}

Write-Log "[3/3] Setting install folder permissions..."
try {
    $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    & icacls $InstallDir /grant "${currentUser}:(OI)(CI)F" /T /Q 2>&1 |
        ForEach-Object { Write-Log "icacls: $_" }
    Write-Log "Full control granted to: $currentUser"
} catch {
    Write-Log "ERROR setting permissions: $_"
}

Write-Log ""
Write-Log "============================================"
Write-Log "Post-install complete"
Write-Log "============================================"
